### ISSUE TITLE
Apperta Foundation GitHub link should be on the top right of the AF website

### ISSUE THREAD

**Issue by pacharanero** [AppertaFoundation/apperta-issues#1]
There should be a prominent link to https://github.com/AppertaFoundation

![image](https://user-images.githubusercontent.com/2348385/35972197-c1df9758-0cc8-11e8-8cc2-c7fc97ebe2c0.png)

**Comment by david-jobling** [comment]
@pacharanero updated
![github](https://user-images.githubusercontent.com/17247691/35972936-7f4c0f04-0ccb-11e8-83ac-73d36a55814b.png)
