### ISSUE TITLE
Add registered office to apperta.org

### ISSUE THREAD

**Issue by robdyke** [AppertaFoundation/apperta-issues#29]
Hey @Apperta @AppertaFoundation/apperta-board-members 

I see that your [registered office moved to Sunderland Software Centre](https://beta.companieshouse.gov.uk/company/09483987/filing-history) back in October.

You need to add the registered address to apperta.org

[apperta-change-reg-office-application-pdf.pdf](https://github.com/AppertaFoundation/apperta-issues/files/2936369/apperta-change-reg-office-application-pdf.pdf)

**Comment by Apperta** [comment]
Thanks Rob, this has now been corrected.

**Comment by robdyke** [comment]
Nearly!

https://github.com/AppertaFoundation/apperta.org/commit/b574e3806a12ca5539e88ceb42a8dcf722b0d542#r32616144
