### ISSUE TITLE
Apperta website could be migrated to static site on GitHub

### ISSUE THREAD

**Issue by pacharanero** [AppertaFoundation/apperta-issues#5]
Here is a link to some information about setting up GitHub hosted static sites with SSL (HTTPS)

https://www.jonathan-petitcolas.com/2017/01/13/using-https-with-custom-domain-name-on-github-pages.html

**Comment by Apperta** [comment]
Apperta Foundation website hosted on github at [https://github.com/AppertaFoundation/apperta.org](https://github.com/AppertaFoundation/apperta.org) and available at [https://apperta.org](https://apperta.org)
